name: CI

on:
  push:
    branches: [master]
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
  pull_request:
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # windows-latest
          - macos-14
    steps:
      - name: Set up repository
        uses: tree-sitter/parser-setup-action@v1.1
        with:
          node-version: ${{vars.NODE_VERSION}}
      - name: Clone neovim runtime
        uses: actions/checkout@v4
        with:
          repository: neovim/neovim
          path: .tests/neovim
          sparse-checkout: runtime/
      - name: Run tests
        uses: tree-sitter/parser-test-action@v1.2
        with:
          lint: true
          corpus-files: |-
            .tests/neovim/runtime/**/*.vim
            !.tests/neovim/runtime/autoload/ada.vim
            !.tests/neovim/runtime/autoload/adacomplete.vim
            !.tests/neovim/runtime/autoload/context.vim
            !.tests/neovim/runtime/autoload/decada.vim
            !.tests/neovim/runtime/autoload/gnat.vim
            !.tests/neovim/runtime/autoload/gzip.vim
            !.tests/neovim/runtime/autoload/javascriptcomplete.vim
            !.tests/neovim/runtime/autoload/msgpack.vim
            !.tests/neovim/runtime/autoload/netrw.vim
            !.tests/neovim/runtime/autoload/netrwSettings.vim
            !.tests/neovim/runtime/autoload/phpcomplete.vim
            !.tests/neovim/runtime/autoload/provider/clipboard.vim
            !.tests/neovim/runtime/autoload/provider/perl.vim
            !.tests/neovim/runtime/autoload/provider/python3.vim
            !.tests/neovim/runtime/autoload/provider/ruby.vim
            !.tests/neovim/runtime/autoload/python3complete.vim
            !.tests/neovim/runtime/autoload/shada.vim
            !.tests/neovim/runtime/autoload/spellfile.vim
            !.tests/neovim/runtime/autoload/tar.vim
            !.tests/neovim/runtime/autoload/tutor.vim
            !.tests/neovim/runtime/autoload/zip.vim
            !.tests/neovim/runtime/compiler/bdf.vim
            !.tests/neovim/runtime/compiler/mcs.vim
            !.tests/neovim/runtime/ftoff.vim
            !.tests/neovim/runtime/ftplugin/abaqus.vim
            !.tests/neovim/runtime/ftplugin/changelog.vim
            !.tests/neovim/runtime/ftplugin/debchangelog.vim
            !.tests/neovim/runtime/ftplugin/forth.vim
            !.tests/neovim/runtime/ftplugin/gdscript.vim
            !.tests/neovim/runtime/ftplugin/gpg.vim
            !.tests/neovim/runtime/ftplugin/markdown.vim
            !.tests/neovim/runtime/ftplugin/mermaid.vim
            !.tests/neovim/runtime/ftplugin/modconf.vim
            !.tests/neovim/runtime/ftplugin/muttrc.vim
            !.tests/neovim/runtime/ftplugin/python.vim
            !.tests/neovim/runtime/ftplugin/readline.vim
            !.tests/neovim/runtime/ftplugin/ruby.vim
            !.tests/neovim/runtime/ftplugin/rust.vim
            !.tests/neovim/runtime/ftplugin/sshconfig.vim
            !.tests/neovim/runtime/ftplugin/sudoers.vim
            !.tests/neovim/runtime/ftplugin/udevrules.vim
            !.tests/neovim/runtime/ftplugin/vhdl.vim
            !.tests/neovim/runtime/ftplugin/vim.vim
            !.tests/neovim/runtime/ftplugin/zig.vim
            !.tests/neovim/runtime/ftplugin.vim
            !.tests/neovim/runtime/ftplugof.vim
            !.tests/neovim/runtime/indent/ada.vim
            !.tests/neovim/runtime/indent/dylan.vim
            !.tests/neovim/runtime/indent/javascript.vim
            !.tests/neovim/runtime/indent/krl.vim
            !.tests/neovim/runtime/indent/php.vim
            !.tests/neovim/runtime/indent/rapid.vim
            !.tests/neovim/runtime/indent.vim
            !.tests/neovim/runtime/indoff.vim
            !.tests/neovim/runtime/keymap/*.vim
            !.tests/neovim/runtime/makemenu.vim
            !.tests/neovim/runtime/menu.vim
            !.tests/neovim/runtime/pack/dist/opt/swapmouse/plugin/swapmouse.vim
            !.tests/neovim/runtime/pack/dist/opt/termdebug/plugin/termdebug.vim
            !.tests/neovim/runtime/plugin/shada.vim
            !.tests/neovim/runtime/syntax/**/*.vim
